apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "demoapp30"
  namespace: "client-apps"
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: "demoapp30"
  template:
    metadata:
      labels:
        app: "demoapp30"
    spec:
      containers:
      - name: "demoapp30"
        image: "registry.gitlab.com/home-server5364202/demo:latest"
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: "pull-secret-demoapp30"
