apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "demojoj"
  namespace: "client-apps"
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: "demojoj"
  template:
    metadata:
      labels:
        app: "demojoj"
    spec:
      containers:
      - name: "demojoj"
        image: "registry.gitlab.com/home-server5364202/demo:latest"
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: "demojoj-config"
        - secretRef:
            name: "demojoj-env-secret"
      imagePullSecrets:
      - name: "pull-secret-demojoj"
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "demojoj-svc"
  namespace: "client-apps"
spec:
  type: "ClusterIP"
  selector:
    app: "demojoj"
  ports:
  - port: 80
    targetPort: 8010
---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "demojoj-config"
  namespace: "client-apps"
---
apiVersion: "networking.k8s.io/v1"
kind: "Ingress"
metadata:
  name: "demojoj-ingress"
  namespace: "client-apps"
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/rewrite-target: "/"
spec:
  ingressClassName: "nginx"
  rules:
  - host: "demojoj-gjs0p3.naboulsiamine.com"
    http:
      paths:
      - path: "/"
        pathType: "Prefix"
        backend:
          service:
            name: "demojoj-svc"
            port:
              number: 80
  tls:
  - hosts:
    - "demojoj-gjs0p3.naboulsiamine.com"
    secretName: "demojoj-tls"
