apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "db-mohamed-1772369448212"
  namespace: "client-apps"
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: "db-mohamed-1772369448212"
  template:
    metadata:
      labels:
        app: "db-mohamed-1772369448212"
    spec:
      containers:
      - name: "db-mohamed-1772369448212"
        image: "mysql:8.0"
        ports:
        - containerPort: 3306
        env:
        - name: "MYSQL_DATABASE"
          value: "mohamed"
        - name: "MYSQL_USER"
          value: "sokry"
        - name: "MYSQL_PASSWORD"
          value: "@Sokry123456789@"
        - name: "MYSQL_ROOT_PASSWORD"
          value: "@Sokry123456789@"
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "db-mohamed-1772369448212-svc"
  namespace: "client-apps"
spec:
  type: "NodePort"
  selector:
    app: "db-mohamed-1772369448212"
  ports:
  - port: 3306
    targetPort: 3306
    nodePort: 31303
